# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
branches:
  only:
    - circleci
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/antonve/logger-api
    steps:
      - run: sudo add-apt-repository ppa:masterminds/glide -y
      - run: sudo apt-get update
      - run: sudo apt-get install glide -y
      - run: checkout
      - run: cp "$APP_PATH/config/test.yml.ci" "$APP_PATH/config/test.yml"
      - run: cd "$APP_PATH" && glide install
      - run: go test -cover $(glide nv)
